[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet Market.dll"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
port = "80"

[env]
ASPNETCORE_ENVIRONMENT = "Production"